# Generated by Django 6.0.1 on 2026-02-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='chosen_theme',
            field=models.CharField(choices=[('latte', 'Latte'), ('frappe', 'Frappé'), ('macchiato', 'Macchiato'), ('mocha', 'Mocha')], default='mocha', max_length=9),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='linked_gmail',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
