[project]
name = "reservoir"
version = "0.1.0"
description = "A puzzlehunt management webapp used by ℙoNDeterministic."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.3",
    "channels-redis>=4.3.0",
    "channels[daphne]>=4.3.2",
    "django>=6.0.1",
    "dotenv>=0.9.9",
    "gspread>=6.2.1",
    "requests>=2.32.5",
    "shunting-yard>=1.0.12.post1",
    "sympy>=1.14.0",
    "whitenoise>=6.11.0",
]

[dependency-groups]
dev = [
    "django-debug-toolbar>=6.2.0",
]
prod = [
    "gunicorn>=24.1.1",
]

# stop uv from trying to build/install this, as it isn't a package
[tool.uv]
package = false

# uv doesn't lock build systems; these are needed by uv2nix to build the sdist-only packages below from source.
[tool.uv.extra-build-dependencies]
py-ubjson = ["setuptools"]
shunting-yard = ["setuptools"]
