# Generated by Django 6.0.1 on 2026-01-24 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('team_user', models.CharField(max_length=64)),
                ('team_pw', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.hunt')),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('LO', 'Locked'), ('NS', 'Not Started'), ('IP', 'In Progress'), ('ST', 'Stuck'), ('EX', 'Now Extract Somehow'), ('SL', 'Solved')], default='LO', max_length=2)),
                ('hunt_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.round')),
            ],
        ),
    ]
