# Generated by Django 6.0.1 on 2026-01-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='is_meta',
            field=models.BooleanField(default=False),
        ),
    ]
