# Generated by Django 6.0.1 on 2026-02-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0003_puzzle_is_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='sheet_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
