# Generated by Django 6.0.1 on 2026-02-03 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0004_puzzle_sheet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='hunt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='puzzles.hunt'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PuzzleRoundField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hunt_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.round')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.puzzle')),
            ],
        ),
        migrations.AddField(
            model_name='puzzle',
            name='rounds',
            field=models.ManyToManyField(through='puzzles.PuzzleRoundField', to='puzzles.round'),
        ),
        migrations.AddConstraint(
            model_name='puzzleroundfield',
            constraint=models.UniqueConstraint(fields=('puzzle', 'hunt_round'), name='no_duplicate_links'),
        ),
    ]
