# Generated by Hand on 2026-02-03 04:12

import django.db.models.deletion
from django.db import migrations, models


def fix_rounds(apps, schema_editor):
    Puzzle = apps.get_model("puzzles", "Puzzle")
    for puzzle in Puzzle.objects.all():
        puzzle.rounds.add(puzzle.hunt_round)
        puzzle.hunt = puzzle.hunt_round.hunt
        puzzle.save()

class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0005_multiway_rounds_schema'),
    ]

    operations = [
        migrations.RunPython(fix_rounds),
        migrations.RemoveField(
            model_name='puzzle',
            name='hunt_round',
        ),
    ]