# Generated by Django 6.0.1 on 2026-02-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0007_discorduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
