# Generated by Django 6.0.1 on 2026-02-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0007_chatmessage'),
        ('puzzles', '0008_puzzle_description'),
    ]

    operations = [
    ]
