# Generated by Django 6.0.1 on 2026-02-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0009_merge_0007_chatmessage_0008_puzzle_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='chat_color',
            field=models.CharField(choices=[('rosewater', 'Rosewater'), ('flamingo', 'Flamingo'), ('pink', 'Pink'), ('mauve', 'Mauve'), ('red', 'Red'), ('maroon', 'Maroon'), ('peach', 'Peach'), ('yellow', 'Yellow'), ('green', 'Green'), ('teal', 'Teal'), ('sky', 'Sky'), ('sapphire', 'Sapphire'), ('blue', 'Blue'), ('lavender', 'Lavender')], default='blue', max_length=9),
        ),
    ]
