# Generated by Django 6.0.1 on 2026-05-23 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0011_chatmessage_is_system_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=16)),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.hunt')),
            ],
        ),
    ]
