# Generated by Django 6.0.1 on 2026-05-23 20:45

import functools
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0012_authlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authlink',
            name='id',
        ),
        migrations.AlterField(
            model_name='authlink',
            name='string',
            field=models.CharField(default=functools.partial(secrets.token_urlsafe, 16), max_length=16, primary_key=True, serialize=False),
        ),
    ]
