# Generated by Django 6.0.1 on 2026-05-23 20:46

import functools
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0013_remove_authlink_id_alter_authlink_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authlink',
            name='string',
            field=models.CharField(default=functools.partial(secrets.token_hex, 16), max_length=32, primary_key=True, serialize=False),
        ),
    ]
