# Generated by Django 6.0.1 on 2026-08-27 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0014_alter_authlink_string'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HuntMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.hunt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hunt',
            name='users',
            field=models.ManyToManyField(through='puzzles.HuntMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='huntmember',
            constraint=models.UniqueConstraint(fields=('user', 'hunt'), name='user_to_hunt'),
        ),
    ]
